export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const NEW_DATA = 'NEW_DATA';
export const NEW_IMAGE = 'NEW_IMAGE';
